pipeline {
    agent any

    environment {
        VENV = 'venv'
        DJANGO_SETTINGS_MODULE = 'messaging_app.settings'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/alidrisy/alx-backend-python.git'
            }
        }

        stage('Git Branch Info') {
            steps {
                sh 'git rev-parse --abbrev-ref HEAD'
            }
        }

        stage('Setup Environment') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m venv $VENV'
                    sh './venv/bin/pip install --upgrade pip'
                    sh './venv/bin/pip install -r requirements.txt'
                }
            }
        }

        stage('Run Migrations') {
            steps {
                dir('messaging_app') {
                    sh './venv/bin/python manage.py migrate'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh './venv/bin/pytest --ds=messaging_app.settings --junitxml=test-results/results.xml'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'messaging_app/test-results/results.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'messaging_app/test-results/*.xml', fingerprint: true
        }
    }
}
