#!/bin/bash

# اسم الدبلويمنت لتطبيق Django (غيّر الاسم حسب اسم دبلويمنتك)
DEPLOYMENT_NAME="messaging_app"

NAMESPACE="default"

kubectl scale deployment "$DEPLOYMENT_NAME" --replicas=3 -n "$NAMESPACE"

kubectl rollout status deployment "$DEPLOYMENT_NAME" -n "$NAMESPACE"

kubectl get pods -n "$NAMESPACE" -l app="$DEPLOYMENT_NAME"

APP_URL="http://localhost/"

wrk -t2 -c50 -d30s "$APP_URL"

kubectl top pods -n "$NAMESPACE" -l app="$DEPLOYMENT_NAME"

