apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging_app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging_app
      version: blue
  template:
    metadata:
      labels:
        app: messaging_app
        version: blue
    spec:
      containers:
        - name: messaging_app
          image: messaging_app-web:2.0  
          ports:
            - containerPort: 3000
