apiVersion: v1
kind: Service
metadata:
  name: messaging_app-service
spec:
  type: NodePort
  selector:
    app: messaging_app
    version: blue  # change to green to switch traffic
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000
